name: Python package with Poetry

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Build package
      run: make build

    - name: Publish to PyPI
      if: github.ref == 'refs/heads/main'
      run: make publish
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
